const COUNTRY_LABELS_ES: Record<string, string> = {
  algeria: "Argelia",
  argentina: "Argentina",
  australia: "Australia",
  austria: "Austria",
  belgium: "Bélgica",
  "bosnia-herzegovina": "Bosnia y Herzegovina",
  "bosnia and herzegovina": "Bosnia y Herzegovina",
  brazil: "Brasil",
  canada: "Canadá",
  "cape verde islands": "Cabo Verde",
  colombia: "Colombia",
  "congo dr": "RD Congo",
  croatia: "Croacia",
  curaçao: "Curaçao",
  czechia: "Chequia",
  ecuador: "Ecuador",
  egypt: "Egipto",
  england: "Inglaterra",
  france: "Francia",
  germany: "Alemania",
  ghana: "Ghana",
  haiti: "Haití",
  iran: "Irán",
  iraq: "Irak",
  "ivory coast": "Costa de Marfil",
  "cote d'ivoire": "Costa de Marfil",
  "côte d'ivoire": "Costa de Marfil",
  japan: "Japón",
  jordan: "Jordania",
  mexico: "México",
  morocco: "Marruecos",
  netherlands: "Países Bajos",
  "new zealand": "Nueva Zelanda",
  norway: "Noruega",
  panama: "Panamá",
  paraguay: "Paraguay",
  portugal: "Portugal",
  qatar: "Catar",
  "saudi arabia": "Arabia Saudita",
  scotland: "Escocia",
  senegal: "Senegal",
  "south africa": "Sudáfrica",
  "south korea": "Corea del Sur",
  spain: "España",
  sweden: "Suecia",
  switzerland: "Suiza",
  tunisia: "Túnez",
  turkey: "Turquía",
  uruguay: "Uruguay",
  "united states": "Estados Unidos",
  "united states of america": "Estados Unidos",
  usa: "Estados Unidos",
  uzbekistan: "Uzbekistán",
};

export function getCountryLabel(teamName: string, locale: string) {
  if (!locale.startsWith("es")) {
    return teamName;
  }

  const normalized = teamName.trim().toLowerCase();
  return COUNTRY_LABELS_ES[normalized] ?? teamName;
}
